dist: xenial

language: python

cache: pip

python:
    - "3.7"


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  
  
install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pipenv install --dev
    
script:
  - bash deploy.sh
