name: CI/CD Workflow

# Events and coresponding branches that initiate this workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# job that checks out repo, builds container with dependencies for scripts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v3

      - name: build container and execute entrypoint.sh
        uses: ./Build-container #private action in root directory
        id: #action id/name

     # At a minimum this job should upload artifacts using actions/upload-pages-artifact
      - name: Upload static file # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v1

  # https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site
  # https://github.com/actions/deploy-pages
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
